name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.9.4
        with: { pixi-version: v0.59.0 }
      - name: build documentation
        run: |
          pixi run doc SPHINXOPTS="-W"
